### PR TITLE
catching up to the latest conduit.

### PR DESCRIPTION
**Pull request by kazu-yamamoto**

### CODE REVIEW

**Comment by Whitespace** [comment]
I can confirm this fixes build problems on OS X using a fresh haskell install and `cabal install`

**Comment by hvr** [comment]
@kazu-yamamoto btw, I had to hack in the following modification on top of your changes to keep pronk from following redirects or throwing exceptions just because a non-2xx status was received:

``` diff
diff --git a/app/App.hs b/app/App.hs
index 496d215..c861efc 100644
--- a/app/App.hs
+++ b/app/App.hs
@@ -159,7 +159,7 @@ validateArgs Args{..} = do

 createRequest :: Args -> IO (E.Request (ResourceT IO))
 createRequest Args{..} = do
-  req0 <- E.parseUrl url `catch` \(e::E.HttpException) ->
+  req00 <- E.parseUrl url `catch` \(e::E.HttpException) ->
           fatal $ "could not parse URL - " ++
                 case e of
                   E.InvalidUrlException _ s -> map toLower s
@@ -168,6 +168,7 @@ createRequest Args{..} = do
       check (Just "POST") = return "POST"
       check (Just "PUT")  = return "PUT"
       check _      = fatal "only POST or PUT may have a body"
+      req0 = req00 { E.redirectCount = 0, E.checkStatus = \_ _ -> Nothing }
   case (from_file, literal) of
     (Nothing,Nothing) -> return req0 { E.method = maybe "GET" B.pack method }
     (Just f,Nothing) -> do
```

**Comment by ppurang** [comment]
I can confirm that after an upgrade to haskell platform 7.4.1 (cabal-install version 0.14.0) and checking out kazu-yamamoto 's pronk fork and the branch latest-conduit .. I was finally able to successfully build .. thanks! 

Next I apply  the patch for non 2xx status codes because I had the same problem .. 201s and 204s aren't failures

**Comment by nh2** [comment]
Yep, this builds fine for me as well.

**Comment by bos** [comment]
Thanks, @kazu-yamamoto and @hvr!

**Pull request merged**
